services:
  postgres:
    image: postgres:16-alpine
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: hollow_ether
      POSTGRES_PASSWORD: hollow_ether
      POSTGRES_DB: hollow_ether
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U hollow_ether -d hollow_ether']
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
