services:
  postgres:
    image: postgres:16-alpine
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: ethernetic
      POSTGRES_PASSWORD: ethernetic
      POSTGRES_DB: ethernetic
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ethernetic -d ethernetic']
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
